name: Deploy Vahan MCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: shubham # Replace with your droplet username
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            bash /home/shubham/vahandata/scripts/deploy.sh
